# Generated by Django 3.0.2 on 2020-01-29 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('receiver_email', models.EmailField(default='', max_length=254, verbose_name='收禮者的email')),
                ('receiver_nickname', models.CharField(default='', max_length=200, verbose_name='收禮者的暱稱')),
                ('sender_nickname', models.CharField(default='', max_length=200, verbose_name='送禮者的暱稱')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '年'), (1, '月'), (2, '週')], default=0, null=True, verbose_name='認識多久')),
                ('extra_messages', models.CharField(blank=True, default='', max_length=200, verbose_name='額外想對他/她說的話')),
                ('creator', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='要讓他/她挑選哪三樣禮物呢？', max_length=200, verbose_name='問題')),
                ('required', models.BooleanField(default=True, help_text='這個問題是否必須回答')),
                ('order_in_list', models.IntegerField(default=1)),
                ('multi_choice', models.BooleanField(default=False, verbose_name='是否為多選')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=50, verbose_name='選項')),
                ('order_in_list', models.IntegerField(default=1)),
                ('choice_question', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='survey.ChoiceQuestion')),
            ],
        ),
    ]
