# Generated by Django 3.0.2 on 2020-01-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200129_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='匿名信件', max_length=200),
        ),
    ]
