# Generated by Django 3.0.2 on 2020-02-23 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_answersheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AnswerSheet')),
                ('choice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice_answers', to='survey.Choice')),
                ('choice_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='對應的題目', to='survey.ChoiceQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
